######################################################################
# Automatically generated by qmake (2.01a) dim. mai 2 23:45:25 2010
######################################################################

TEMPLATE = app
TARGET = ../../bin/test_cdbhandling
DEPENDPATH += .
INCLUDEPATH += . ../../src ../../src/interfaces 

QT += testlib sql xml


# Input
SOURCES += testcdbhandling.cpp ../../src/cdbhandling.cpp ../../src/moc_cdbhandling.cpp
