######################################################################
# Automatically generated by qmake (2.01a) ven. juin 13 13:34:08 2008
######################################################################

TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += caccessinterface.h cdbinterface.h cdeviceinterface.h cloginterface.h calarminterface.h
TEMPLATE = subdirs

